# Generated by Django 2.1.3 on 2019-05-17 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='say_something_nice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='voter',
        ),
    ]
